### ISSUE TITLE
Streaming Services

### ISSUE THREAD

**Issue by m4lki3r** [Protektor-Desura/Archon#4]
Requestiong update to the Comparison Page:

Plex can now have "Plugins" as the comparison calls them for Streaming Services

Current Rows
- Amazon Prime Video
- BBC America
- Disney+
- Hulu
- Netflix
- PlutoTV
- YouTube

Additional Big Name

- Apple TV and TV+
- Crunchyroll
- HBO Max
- Paramount+

There are a lot of others, but I'd update the big names here. [Blog Post](https://www.plex.tv/blog/end-the-streaming-struggle-with-plex/)

**Comment by Protektor-Desura** [comment]
Those are not plugins because it only sends to you to their website to watch or it opens their app on your TV, Phone or Tablet. You are not staying inside Plex. Plex has only agents now. They do NOT have any plugins anymore. They got rid of them and posted about plugins going away.

https://techpp.com/2020/05/29/best-plex-plugins-how-to-sideload-guide/
https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/
